---

- hosts: all
  gather_facts: True
  become: true

  tasks:
  - name: Ensure git is installed.
    yum:
      name: git
      state: installed

  roles:
    - ansible-role-nginx
    - ansible-role-repo-epel
    - ansible-role-nodejs
    - ansible-role-mongodb
    - ansible-role-pip
    - ansible-role-supervisor
